const event_data = [
    {
      id: 2,
      name: "Samsung Coding Challenge",
      speaker: null,
      designation: null,
      image: "https://apiv.prometeo.in/media/images/Coding2.jpg",
      rulebook: null,
      problem_statement: "",
      sponsor_image1: null,
      sponsor_website: null,
      participation_type: "individual",
      min_team_size: 1,
      max_team_size: 1,
      prize: "51K INR",
      description:
        '"Coding Challenge" is the event everyone is waiting for. A Techfest can never be complete without a "Coding Competition". So Samsung is here for all technophiles. Get ready to showcase your outstanding competitive programming skills. This is a 12-hour coding competition based on algorithms, data structures, and problem-solving. There are two questions, and participants are ranked according to the number of problems solved and the best solution, and tied in ascending order according to each user\'s total time. Working conditions are in English. So, what are you waiting for? Register for the contest on the official website to win 51,000 worth of prizes and amazing internship opportunities at Samsung.',
      poster_description: "",
      host: null,
      external_link: null,
      date: "2022-11-06",
      time: "15:11:22",
      end_date: "2022-11-06",
      end_time: "15:11:23",
      venue: null,
      registration_open: true,
      type: "technical",
      event_started: false,
      meet_link: null,
      youtube_link: null,
      webx_link: null,
      featured: false,
      rank: 1,
      hidden: false,
      presentation_template: null,
      sample_poster: null,
      submissions_started: false,
      submission_link: null,
      material_name: null,
      material: null,
    },
]
export default event_data;