const flagshipEvents_data = [
  {
    id: 1,
    name: "DroneRace",
    speaker: null,
    designation: null,
    bg_image:
      "https://cdn2.unrealengine.com/egs-thedroneracingleaguesimulator-thedroneracingleague-g1a-03-1920x1080-d178ef71f4cf.jpg",
    image: "https://video-public.canva.com/VAFBGKGj3xU/v/192739a542.gif",
    cardbg1: "https://techfest.org/static/resources/robowars/robowars_bots.jpg",
    cardbg2: "https://techfest.org/static/resources/robowars/robowar60.jpeg",
    sponsors: ["https://apiv.prometeo.in/media/sponsors/smasung_sWRoaY5.webp"],
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "51K INR",
    description:
      "For the first time in the history of Prometeo organizing North-Western India’s Largest FPV Drone Racing League.Brace yourselves for one of the most elite extravaganza events Night Drone Racing at Prometeo IIT Jodhpur and witness the drones slicing through the air with absolute speed.Don't miss this opportunity to see drones soaring through the air at top speed in this exciting. All races will be governed by an appointed team of judges/organizers. Each race will be monitored by judges, cameras, timing/lap systems and volunteers to maintain fair and accurate competition",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "15:11:22",
    end_date: "2022-11-06",
    end_time: "15:11:23",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
];
export default flagshipEvents_data;
