const event_data = [
  {
    id: 2,
    name: "Samsung Coding Challenge",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/Coding2.jpg",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "51K INR",
    description:
      '"Coding Challenge" is the event everyone is waiting for. A Techfest can never be complete without a "Coding Competition". So Samsung is here for all technophiles. Get ready to showcase your outstanding competitive programming skills. This is a 12-hour coding competition based on algorithms, data structures, and problem-solving. There are two questions, and participants are ranked according to the number of problems solved and the best solution, and tied in ascending order according to each user\'s total time. Working conditions are in English. So, what are you waiting for? Register for the contest on the official website to win 51,000 worth of prizes and amazing internship opportunities at Samsung.',
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "15:11:22",
    end_date: "2022-11-06",
    end_time: "15:11:23",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 4,
    name: "I Code U",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/I_code_U_y7zvT1h.png",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "35K INR",
    description:
      "As soon as we hear the word 'Tech', the thing that comes to our mind is 'code' and how can one expect to conduct a Techfest without a 'Coding Competition'. So, all the cyberpunks out there gear up to show your excellent competitive programming skills. The coding competition is based on Algorithms, Data structures and Problem Solving. The participants will be ranked as per the number of problems solved and the ties will be broken by the total time for each user in ascending order. The problem statements will be in English. So, what are you waiting for? Do register for the contest on our official website and get a chance to win amazing prizes and goodies.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "15:55:09",
    end_date: "2022-11-06",
    end_time: "15:55:11",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 5,
    name: "Kaggle Knight",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/kaggle.png",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "75K INR",
    description:
      "What happens when you hear the words “Data Science” and “Machine Learning”? Isn’t it futuristic tech that comes to your mind?. Indeed, they will have a huge role in our lives in upcoming times. We present to you a platform to test your enthusiasm. Data-science and Machine Learning enthusiasts prime yourselves for a Kaggle competition. It is a 36 hour long thrilling hackathon from 26th February to 27th February. You will be asked to solve tasks of varying complexities designed by experts and the participants coming up with the most innovative and efficient solutions will be rewarded.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:28:50",
    end_date: "2022-11-06",
    end_time: "16:28:51",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 6,
    name: "Wired",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/Events_template_4_8Cp5tya.png",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "35K INR",
    description:
      "Back to the Future!\r\nAre you someone who likes to build things? From building blinking LED lights to setting up the mighty megazord. Do you think you’ve got it all? We present before you an opportunity you’ve all been waiting for, an Arduino competition. We have compiled a set of challenges that’ll set your brain to tinker in the most arduous manner you could ever imagine.\r\nThese challenges are open to all college students and require individual participation. The problem statement will be shared just before the event starts, any plagiarism will lead to disqualification.\r\nAll team members are supposed to ideate and design circuits basing on Arduino UNO as a major component. Most efficient and innovative designs will be rewarded with extra credit!\r\nWe would like you to put your best foot forward at this upcoming event. Hope to see you there!",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:37:47",
    end_date: "2022-11-06",
    end_time: "16:37:49",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 7,
    name: "Scavenger Hunt",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/14_NMTBKNj.png",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "35K INR",
    description:
      "Problem solving is a skill everyone should have in their lives. If you do not have one, now is the time to possess such powers. For all the gaming aficionados, prometeo has come with a Tech Scavenger Hunt competition which will allow you to practice problem solving in a tangible way. You will be provided with a sequence of locked questions where the key to the next question is the answer of the previous question. The team taking the least time to reach the end wins. This competition certainly will let you learn with fun.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:36:51",
    end_date: "2022-11-06",
    end_time: "16:36:53",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 8,
    name: "Blockchain Hackathon",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/Prometeo-Blockchain-01_1.png",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "75k INR",
    description:
      "Want to explore the world of apps? Does software development fascinate you? We bring to you this series of exciting hackathons, where Web and App developers will get a chance to build the product according to the requirements given by the experts of the domain. These hackathons help you put your coding and development skills to work and solve interesting problems and real-life challenges. Team size to be from 1-3 members. Use of online website makers and app makers is not allowed. Freshen up yourself to get floated in the world of apps. Some of the hackathons will need you to participate in teams and this provides a great opportunity to put your leadership skills to the fore, inspire and motivate your team. See ya!",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:40:30",
    end_date: "2022-11-06",
    end_time: "16:40:31",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 9,
    name: "TechBuzz",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/Tech_Quiz-01_SwQRSTy.png",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "35K INR",
    description:
      "Are you a techie? We knew it! So here we are providing you with a tremendous opportunity to pique your passion for technology. Hold your horses and prepare for the ride ahead. We're thrilled to host a two-round quiz contest with a tech theme. Both Prelims and Finals will be conducted entirely ONLINE. To win the title and spectacular prizes, each team is expected to answer the questions asked as quickly as possible. Equip yourself and remember to sharpen up your Science and Technology wisdom before the day of reckoning. On the other end, we hope to see you!",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:41:47",
    end_date: "2022-11-06",
    end_time: "16:41:50",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 10,
    name: "Capture The Flag",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/hackathon.jpg",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "57K INR",
    description:
      "The top three winners will get guaranteed 50,000+ INR internships and the Top 10 winners will get goodies and course enrollments worth 2,00,000 INR. Want to explore the world of apps? Does software development fascinate you? We bring to you this series of exciting hackathons, where Web and App developers will get a chance to build the product according to the requirements given by the experts of the domain. These hackathons help you put your coding and development skills to work and solve interesting problems and real-life challenges. The basic challenge is to search for 3 flags hidden in the machines that will be given to each participant, within a limited time of two hours. The participant will be ranked based on the time taken to capture each flag. Each participant will be given only an IP address and no other information.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:42:59",
    end_date: "2022-11-06",
    end_time: "16:43:01",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 11,
    name: "CADASTROPHE",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/Events_template_1_akvaRJg.png",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "35K INR",
    description:
      "If you can think it, you can make it, you're only limited by your imagination! Designing a project is as important as executing it, and is considered as the vital step to any project. The art of designing and modeling things is a gift, a gift known to a very few people of the society. Are you one of those? Why wait then, we’ve got you covered. We are organizing a CAD Night for all of you design nerds waiting for the correct opportunity to showcase your talent where you will be provided with a problem statement for a particular design and you need to be done with the task in 48hrs.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:44:08",
    end_date: "2022-11-06",
    end_time: "16:44:10",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 12,
    name: "Samsung NLP Challenge",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/rm373batch5-20_WM3p2q9.jpg",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "51K INR",
    description:
      "Data Science and Machine learning terms strike through the mind as we hear about futuristic world. Indeed, they will have a huge role in our lives in upcoming times. Everyone is looking forward to it. So, Samsung presents to you a challenge to test your enthusiasm. Data-science and NLP enthusiasts prime yourselves for a challenge. The participants will be asked to solve tasks of varying complexities designed by experts and the participants coming up with the most innovative and efficient solutions will be rewarded with prizes and internship opportunities by Samsung.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:46:19",
    end_date: "2022-11-06",
    end_time: "16:46:21",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 13,
    name: "Tech Press",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/Article_Writing-01.png",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "35K INR",
    description:
      "Literature is delightful to read while technology is intriguing. Wonder what would happen if the two ought to converge? Undoubtedly that would be spectacular. So, for all those literature aficionados and voracious readers who are also captivated by technology, we have a terrific opportunity for you to explore, engage, and earn rewards. We announce an article writing competition based on the tech theme. The contestants must write an article which is easy to understand and should not be a research article. Of course, the most remarkable article, one that would blow the judges' minds, has to be the winner, and that person will have a lot in store for themselves. So, what are you still waiting for? Get your pens out, polish up on your skills and knowledge, and keep training. Also, don't forget to join so you can showcase your writing abilities. See you there!",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:47:14",
    end_date: "2022-11-06",
    end_time: "16:47:17",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 14,
    name: "Business Darbar",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/BD4_9X4bnod_Lm3XXmt.jpg",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "50K INR",
    description:
      "Starting a new venture is a challenge and it is quite frequent that young founders lack proper mentorship and often do basic mistakes which could be extremely threatening to the future of their venture. \r\n\r\nThis is a Shark Tank formatted pitching event where student entrepreneurs could come to pitch their venture. There would be a panel of 3-5 Angel Investors, Venture Capitalists and Industry Experts who'll help students and provide them personal mentorship and some investment offers. Startups could be at any stage with their business, Ideation, MVP, PMF etc\r\n\r\nNeed a hint? The Marauder’s map reveals everything, including the next clue, you just need to say the password to the map. However the password has changed. Maybe this can help you out manage your mischiefs 158962555217826360000.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:48:59",
    end_date: "2022-11-06",
    end_time: "16:49:02",
    venue: null,
    registration_open: true,
    type: "entrepreneurial",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 16,
    name: "Biz Quiz",
    speaker: null,
    designation: null,
    image: "https://apiv.prometeo.in/media/images/biz_quiz_UbTBzEV_F9zeVd3.png",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "25K INR",
    description:
      "For all the quiz enthusiasts and the ones who would love to assess their knowledge in the fields of Entrepreneurship, Marketing, Finance, Social Entrepreneurship, Fintech, startups and Share Markets, Promoteo brings Biz Quiz for you!\r\n\r\nBiz Quiz is a unique way and exciting way to encourage, motivate and reward the students who are having good grasp in the mentioned fields.\r\n\r\nWhat are you waiting for you then ? All you need to do is to get yourself registered with the quiz competition and show up. Get yourself ready to challenge the bright minds from the top colleges across the country!",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:52:12",
    end_date: "2022-11-06",
    end_time: "16:52:14",
    venue: null,
    registration_open: true,
    type: "entrepreneurial",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 17,
    name: "Pranalika",
    speaker: null,
    designation: null,
    image:
      "https://apiv.prometeo.in/media/images/business-plan-strategy-development-process-graphic-concept_1_h281fwI_APiEiWS.jpg",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "60K INR",
    description:
      "Are you the one who loves the idea of spearheading something innovative? Prometeo brings Pranalika for you! A 48-hour long ideathon focuses on futuristic field of IoT. Pranalika will surf you through this exciting ride of creativity to design and build an envisioning future. It trains your brain for a perfect business plan tinkers your senses to bring out a real-time, field-based problem of Samsung given and evaluated by industry experts. A confluence of innovation and reality for cushioning the future of the world. An excellent bumper cash prize for the cream of the cream!",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "16:53:14",
    end_date: "2022-11-06",
    end_time: "16:53:16",
    venue: null,
    registration_open: true,
    type: "entrepreneurial",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
];

// var cardPhoto = document.getElementsByClassName('card__photo');
// var cardTitle = document.querySelectorAll('h2');

// for (var i = 0; i < cardPhoto.length; i++){
// cardPhoto[i].src = data[i].image;
// cardTitle[i].innerHTML = data[i].name;
// }

export default event_data;
