const data = [
  {
    id: 1,
    name: "Prometeo-23-logo",
    description: null,
    type: "image",
    image: "https://apiv.prometeo.in/media/gallery/images/prometeo_logo_23-min.png",
    video: null,
    rank: 1,
    hidden: true,
  },
  {
    id: 2,
    name: "Image1",
    description: null,
    type: "image",
    image: "https://apiv.prometeo.in/media/gallery/images/Image1.jpg",
    video: null,
    rank: 1,
    hidden: true,
  },
  {
    id: 3,
    name: "Image2",
    description: null,
    type: "image",
    image: "https://apiv.prometeo.in/media/gallery/images/image2.jpg",
    video: null,
    rank: 2,
    hidden: true,
  },
  {
    id: 4,
    name: "Image3",
    description: null,
    type: "image",
    image: "https://apiv.prometeo.in/media/gallery/images/Image3.jpg",
    video: null,
    rank: 3,
    hidden: true,
  },
  {
    id: 5,
    name: "Image4",
    description: null,
    type: "image",
    image: "https://apiv.prometeo.in/media/gallery/images/Image4.jpg",
    video: null,
    rank: 1,
    hidden: true,
  },
  {
    id: 6,
    name: "Image5",
    description: null,
    type: "image",
    image: "https://apiv.prometeo.in/media/gallery/images/Image5.jpg",
    video: null,
    rank: 1,
    hidden: true,
  },
];

export default data;