const team_data = [
    {
        teamName: "Public Relations",
        members: [
            {
                id: 0,
                image: "https://i.imgur.com/DWO7yNR.jpg",
                name: "Abu Shahid ",
                por: "Head",
                phone: "8840836373",
                mail: "shahid.3@iitj.ac.in",
                instagram: "https://www.instagram.com/ceyxasm/",
                linkedin: "",
                github: "",
            },
            {
                id: 1,
                image: "https://i.imgur.com/2zLMQCB.jpg",
                name: "Tanmay",
                por: "Head",
                phone: "8368753323",
                mail: "tanmay.1@iitj.ac.in ",
                instagram: "https://www.instagram.com/1__tanmay__/",
                linkedin: "",
                github: "",
            },
            {
                id: 2,
                image: "https://i.imgur.com/MV241a1.jpg",
                name: "Yashmita",
                por: "Head",
                phone: "7015696881",
                mail: "yashmita.1@iitj.ac.in",
                instagram: "https://www.instagram.com/Yashmita__sangwan/",
                linkedin:
                    "https://in.linkedin.com/in/yashmita-sangwan-6a403820a",
                github: "",
            },
            {
                id: 3,
                image: "https://i.imgur.com/DG2w36d.jpg",
                name: "Ayush Didel",
                por: "Head",
                phone: "7725973739",
                mail: "didel.1@iitj.ac.in",
                instagram:
                    "https://instagram.com/didelayush2003?igshid=YmMyMTA2M2Y=",
                linkedin: "https://www.linkedin.com/in/ayush-didel-64087b220",
                //Public Relations
            },
        ],
    },
    {
        teamName: "Technical events",
        members: [
            {
                id: 0,
                image: "https://i.imgur.com/Z1gn8Wu.jpg",
                name: "Adarsh Palaskar ",
                por: "Head",
                mail: "palaskar.1@iitj.ac.in",
                instagram: "https://www.instagram.com/adarsh_palaskar99",
                linkedin: "https://www.linkedin.com/in/adarsh-palaskar/",
            },
            {
                id: 1,
                image: "https://i.imgur.com/AW0d3d5.jpg",
                name: "Sumit Kumar Prajapati",
                por: "Head",
                mail: "prajapati.3@iitj.ac.in",
                instagram: "https://www.instagram.com/the.sumitprajapati/",
                linkedin:
                    "https://www.linkedin.com/in/sumit-prajapati-2a0a551bb/",
            },
            {
                id: 2,
                image: "https://i.imgur.com/E6AmTLq.jpg",
                name: "Likhith Ayinala",
                mail: "ayinala.1@iitj.ac.in",
                instagram: "https://instagram.com/likhith_25603?igshid=NTA5ZTk1NTc=",
                linkedin: "https://www.linkedin.com/in/likhith-ayinala-4ba7441b9/",
            }
        ],
    },
    {
        teamName: "Tech Carnival",
        members: [
            {
                id: 1,
                image: "https://i.imgur.com/ZjdLbgK.jpg",
                name: "Somil Maheshwari ",
                por: "Head",
                mail: "maheshwari.7@iitj.ac.in",
                instagram: "https://www.instagram.com/somil_maheshwari/",
                linkedin: "",
            },
        ],
    },
    {
        teamName: "Entrepreneurial events",
        members: [
            {
                id: 0,
                image: "https://i.imgur.com/V6JhE4z.jpg",
                name: "Harshita Kalani",
                por: "Head",
                mail: "kalani.1@iitj.ac.in",
                instagram: "https://www.instagram.com/harsheyyyy_11/",
                linkedin:
                    "https://www.linkedin.com/in/harshita-kalani-604866225?trk=public_profile_samename-profile&originalSubdomain=in",
            },
            {
                id: 1,
                image: "https://i.imgur.com/kLW8SyF.jpg",
                name: "Jaimin Gajjar",
                por: "Head",
                mail: "jaimingajjar01@gmail.com",
                instagram: "https://www.instagram.com/jaimin002/",
                linkedin: "http://linkedin.com/in/jaimin-gajjar-0386b31b9",
            },
            {
                id: 2,
                image: "https://i.imgur.com/BxTVz9t.png",
                name: "Tejas Parmar ",
                por: "Head",
                mail: "parmar.2@iitj.ac.in",
                instagram:
                    "https://instagram.com/_tejas.parmar?igshid=YmMyMTA2M2Y=",
                linkedin: "https://www.linkedin.com/in/tejas-parmar-990832204",
                //Entrepreneurial events
            },
        ],
    },
    {
        teamName: "Informals",
        members: [
            {
                id: 0,
                image: "https://i.imgur.com/sstMbOd.jpg",
                name: "Ritish Khichi",
                por: "Head",
                mail: "khichi.1@iitj.ac.in",
                instagram: "https://www.instagram.com/ritish.khichi/",
                linkedin: "https://www.linkedin.com/in/ritish-khichi-06a30a209",
                github: "",
            },
            {
                id: 1,
                image: "https://i.imgur.com/zBrnO4l.jpg",
                name: "Bhavya Sharma",
                por: "Head",
                mail: "sharma.91@iitj.ac.in",
                instagram: "https://instagram.com/bms.0212?igshid=YmMyMTA2M2Y=",
                linkedin: "https://www.linkedin.com/in/bhavya-sharma-04772b209",
                github: "",
            },
            {
                id: 2,
                image: "https://i.imgur.com/hUqsKIP.jpg",
                name: "Uday Bhanu ",
                por: "Head",
                mail: "bhanu.2@iitj.ac.in",
                instagram: "https://www.instagram.com/_uday_bhanu_/",
                linkedin: "https://www.linkedin.com/in/uday-bhanu-983653204/",
                //Informals
            },
        ],
    },
    {
        teamName: "Pronite",
        members: [
            {
                id: 0,
                image: "https://i.imgur.com/xkkcmd2.jpg",
                name: "Ayush Abad",
                por: "Head",
                mail: "abad.1@iitj.ac.in",
                instagram: "https://www.instagram.com/Ayush_abad_/",
                linkedin: "",
                github: "",
            },
            {
                id: 1,
                image: "https://i.imgur.com/9ozKlyT.jpg",
                name: "Aman Mithoriya",
                por: "Head",
                mail: "mithoriya.1@iitj.ac.in",
                instagram: "https://www.instagram.com/amanmithoriya/",
                linkedin: "",
                github: "",
            },
        ],
    },
    {
        teamName: "Marketing",
        members: [
            {
                id: 0,
                image: "https://i.imgur.com/KtQhoZH.jpg",
                name: "Harshita Gupta ",
                por: "Head",
                mail: "gupta.75@iitj.ac.in",
                instagram: "",
                linkedin: "",
                github: "",
            },
            {
                id: 1,
                image: "https://i.imgur.com/PpP9GWi.jpg",
                name: "Heet Shah",
                por: "Head",
                mail: "shahheet85@gmail.com",
                instagram: "https://www.instagram.com/shahheet85/",
                linkedin: "https://www.linkedin.com/in/heet-shah-9ab2301b0/",
                github: "",
            },
            {
                id: 2,
                image: "https://i.imgur.com/kVPgMcO.jpg",
                name: "Tanmay Gupta ",
                por: "Head",
                mail: "gupta.80@iitj.ac.in",
                instagram: "https://www.instagram.com/tanmay_gupta__/",
                linkedin: "https://www.linkedin.com/in/tanmay-gupta-502040201/",
                //Marketing
            },
        ],
    },
    {
        teamName: "Design and Creativity ",
        members: [
            {
                id: 0,
                image: "https://i.imgur.com/qYhdB6r.jpg",
                name: "Haardik Ravat",
                por: "Head",
                mail: "ravat.1@iitj.ac.in",
                instagram: "https://instagram.com/haardik_ravat",
                linkedin: "https://www.linkedin.com/in/haardik-ravat",
                github: "",
            },
            {
                id: 1,
                image: "https://i.imgur.com/24rxcmH.jpg",
                name: "Himanshu Parmeshwar",
                por: "Head",
                mail: "parmeshwar.1@iitj.ac.in",
                instagram: "",
                linkedin:
                    "https://www.linkedin.com/in/himanshu-parmeshwar-85234a24a/",
                github: "",
            },
        ],
    },

    {
        teamName: "Content Writing",
        members: [
            {
                id: 0,
                image: "https://i.imgur.com/oPigWVd.jpg",
                name: "Lakshya Nitin Tandon ",
                por: "Head",
                mail: "tandon.1@iitj.ac.in ",
                instagram:
                    "https://instagram.com/alaukik_lnt09?igshid=ZDdkNTZiNTM=",
                linkedin: "",
                github: "",
            },
        ],
    },

    {
        teamName: "Web Development Team",
        members: [
            {
                id: 0,
                image: "https://media-exp1.licdn.com/dms/image/C4D03AQFmmlGQ5EyGBg/profile-displayphoto-shrink_800_800/0/1639395734793?e=1675900800&v=beta&t=jgLKE30oiPsRo1FnYjsQeocABUEmaqWN0bB51YxQGgE",
                name: "Yash Bhargava",
                por: "Front End Head",
                mail: "bhargava.3@iitj.ac.in",
                instagram: "https://instagram.com/cyan_tarantula",
                linkedin: "https://linkedin.com/in/yashbhargava02",
                github: "https://github.com/CyanTarantula",
            },
            {
                id: 1,
                image: "https://i.imgur.com/SraW8K9.jpg",
                name: "Soumil Sinha",
                por: "Front End Head",
                mail: "sinha.5@iitj.ac.in",
                instagram: "https://www.instagram.com/soumil.sinha/",
                linkedin: "https://www.linkedin.com/in/soumil-sinha-979845204/",
                github: "https://github.com/sawmill811",
            },
            {
                id: 2,
                image: "https://i.imgur.com/cAdiPmR.jpg",
                name: "Samkit Shah",
                por: "Back End Head",
                mail: "shah.11@iitj.ac.in",
                instagram: "",
                linkedin: "https://www.linkedin.com/in/samkit-shah-432147209/",
                github: "https://github.com/samkitshah1262",
            },
        ],
    },

    {
        teamName: "App Development Team",
        members: [
            {
                id: 0,
                image: "https://media-exp1.licdn.com/dms/image/C4D03AQEFSqJ1M2MpDw/profile-displayphoto-shrink_800_800/0/1636205452815?e=1675900800&v=beta&t=kkDvsFcfmGQced2pFQLXmYatWZKUu6iWLWkGw4zKa3c",
                name: "Pranav Goswami",
                por: "Head",
                mail: "goswami.4@iitj.ac.in",
                instagram: "https://www.instagram.com/pranav_chiku/",
                linkedin:
                    "https://www.linkedin.com/in/pranav-goswami-30a365207/",
                github: "https://github.com/pranavchiku",
            },
        ],
    },
    {
        teamName: "Publicity and Media",
        members: [
            {
                id: 0,
                image: "https://i.imgur.com/7Xgn3Vp.jpg",
                name: "Divyanshi Singh Bora",
                por: "Head",
                mail: "bora.1@iitj.ac.in",
                instagram: "https://www.instagram.com/bora_divyanshi_/",
                linkedin:
                    "https://www.linkedin.com/in/divyanshi-singh-bora-40a322205/",
                github: "",
            },
            {
                id: 1,
                image: "https://i.imgur.com/Ciree2k.jpg",
                name: "Suborno Biswas",
                por: "Head",
                mail: "biswas.4@iitj.ac.in",
                instagram: "https://www.instagram.com/ivan_biswas/",
                linkedin: "https://www.linkedin.com/in/subornobiswas/",
                github: "",
            },
            {
                id: 2,
                image: "https://i.imgur.com/6DbJuhI.jpg",
                name: "Prajjwal Chand",
                por: "Head",
                mail: "chand.1@iitj.ac.in ",
                instagram:
                    "https://instagram.com/prajjwalchand_?igshid=YmMyMTA2M2Y=",
                linkedin: "https://www.linkedin.com/in/prajjwalchand",
                github: "",
            },
        ],
    },
    {
        teamName: "Accommodation, Transportation and Security",
        members: [
            {
                id: 0,
                image: "https://i.imgur.com/m1jyFCj.jpg",
                name: "Viraj Jagdale ",
                por: "Head",
                mail: "viraj.1@iitj.ac.in",

                instagram: "https://www.instagram.com/virgrammid_8302",
                linkedin: "",
                github: "",
            },
            {
                id: 1,
                image: "https://i.imgur.com/Ey2xo0F.jpg",
                name: "Manasi Dubey",
                por: "Head",
                mail: "dubeymanasi22@gmail.com ",
                instagram: "",
                linkedin: "https://www.linkedin.com/in/manasi-dubey-391335243",
                github: "",
            },
            {
                id: 2,
                image: "https://i.imgur.com/iWFbj9L.jpg",
                name: "Parth Yaduvanshi",
                por: "Head",
                mail: "yaduvanshi.2@iitj.ac.in",
                instagram:
                    "https://instagram.com/parthyadu1shi?igshid=YmMyMTA2M2Y=",
                linkedin:
                    "https://www.linkedin.com/in/parth-yaduvanshi-b84907200",
                github: "",
            },
            {
                id: 3,
                image: "https://i.imgur.com/2dA4z5a.jpg",
                name: "Saiyam Arora",
                por: "Head",
                mail: "arora.9@iitj.ac.in",
                instagram: "https://www.instagram.com/_arora_sam/",
                linkedin: "",
                github: "",
            },
        ],
    },

    {
        teamName: "Resource Management ",
        members: [
            {
                id: 0,
                image: "https://i.imgur.com/3Vlj1iH.jpg",
                name: "Gaurav Sangwan ",
                por: "Head",
                mail: "sangwan.2@iitj.ac.in",
                instagram: "https://www.instagram.com/sangs_gaurav/",
                linkedin: "https://www.linkedin.com/in/gaurav-sangwan",
                github: "",
            },
            {
                id: 1,
                image: "https://i.imgur.com/q3enHeP.jpg",
                name: "Vinayak Verma",
                por: "Head",
                mail: "verma.31@iitj.ac.in",
                instagram: "",
                linkedin: "",
                github: "",
            },
            {
                id: 2,
                image: "https://i.imgur.com/x8vbMnS.jpg",
                name: "Dhruv Gupta",
                por: "Head",
                mail: "gupta.77@iitj.ac.in",
                instagram: "https://www.instagram.com/dhruvgupta_1212/",
                linkedin: "",
                github: "",
            },
            {
                id: 3,
                image: "https://i.imgur.com/eaVTQvM.jpeg",
                name: "Karan Singh Kushwah ",
                por: "Head",
                mail: "kushwah.4@iitj.ac.in ",
                instagram: "https://www.instagram.com/karanrajawat7021/",
                linkedin:
                    "https://www.linkedin.com/in/karan-singh-kushwah-475429219",
                github: "",
            },
        ],
    },

    {
        teamName: "Festival Chiefs",
        members: [
            {
                id: 0,
                image: "https://media-exp1.licdn.com/dms/image/C5603AQGDTRLnyF0SHw/profile-displayphoto-shrink_800_800/0/1641058794143?e=1675900800&v=beta&t=XO1aBlMBolLJ6QA3R_d16ijtmUj04docnpwJVxptoy4",
                name: "Yash Ruhatiya",
                por: "",
                phone: "8605835009",
                mail: "ruhatiya.1@iitj.ac.in",
                instagram:
                    "https://instagram.com/yash_ruhatiya24?igshid=YmMyMTA2M2Y=",
                linkedin: "https://www.linkedin.com/in/yash-ruhatiya-308831206",
                github: "",
            },
            {
                id: 1,
                image: "https://media-exp1.licdn.com/dms/image/C4D03AQGa_1PjeJ7B7g/profile-displayphoto-shrink_800_800/0/1661627598565?e=1675900800&v=beta&t=sqON6g5iuTaGDxzS-f2la7QoemJC87JBLjHNnk7I5NI",
                name: "Dhruv Agarwal",
                por: " ",
                phone: "8741011311",
                mail: "agarwal.18@iitj.ac.in",
                instagram: "https://www.instagram.com/dhruv_3005/",
                linkedin: "https://www.linkedin.com/in/dhruv-agarwal-3480611a7",
                github: "",
            },
            {
                id: 2,
                image: "https://rahulgopathi.tech/assets/img/My%20photo.png",
                name: "Rahul Gopathi",
                por: "",
                phone: "8919430577",
                mail: "gopathi.1@iitj.ac.in",
                instagram: "https://www.instagram.com/rahul_gopathi/",
                linkedin:
                    "https://www.linkedin.com/in/rahul-gopathi-a8084a1b8/",
                github: "",
            },
            {
                id: 3,
                image: "https://i.imgur.com/Srzgz1v.jpg",
                name: "Neielotpal Rao",
                por: " ",
                phone: "7988389822",
                mail: "rao.5@iitj.ac.in",
                instagram: "",
                linkedin: "",
                github: "",
            },
        ],
    },
];

export default team_data;
