const speakerDetails = [
  {
    id: 18,
    name: "Mr. Inderpal Bhandari",
    speaker: "Mr. Inderpal Bhandari",
    designation: "Global Chief Data Officer, IBM Corporation",
    image: "https://apiv.prometeo.in/media/images/Inderpal.jfif",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "NA",
    description:
      "He leads IBM's data strategy to ensure IBM remains the number one AI and hybrid cloud provider for the enterprise. His expertise is to transform data into business value and improve customer experiences by delivering strategic and innovative capabilities that use analytic insights to enable growth and productivity. He was named U.S. Chief Data Officer of the Year by the CDO Club in 2017 and named Corinium's Top 100 Innovators in Data and Analytics in 2018, 2019, and 2020. In 2020, He was also appointed as one of the Global Top 100 Data Visionaries by Truata.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2023-01-01",
    time: "09:00:00",
    end_date: "2022-02-26",
    end_time: "00:00:00",
    venue: "Audi 1",
    registration_open: true,
    type: "talk",
    event_started: true,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: -8080,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 19,
    name: "Mr. Manish Kumar",
    speaker: "Mr. Manish Kumar",
    designation: "CoFounder & CEO - RealX & GreX",
    image: "https://apiv.prometeo.in/media/images/manishKumar.jpg",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "NA",
    description:
      "He is the Vice president of R&D Dassault Syst\\u00e8mes and is recently promoted to CEO of Solidworks. He has exceptional team management abilities to drive planning, development, testing, and implementation of market-leading products. He has provided the leadership needed to transform Solidworks business into an industry-leading SaaS based cloud computing platform.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2023-01-01",
    time: "19:00:00",
    end_date: "2022-02-26",
    end_time: "20:00:00",
    venue: "Audi 1",
    registration_open: true,
    type: "talk",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 20,
    name: "Prof. Jeffrey Ullman",
    speaker: "Prof. Jeffrey Ullman",
    designation: "Professor of Computer Science (Emeritus)",
    image: "https://apiv.prometeo.in/media/images/jeff_ulman.png",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "NA",
    description:
      "He is an American computer scientist and the Stanford W. Ascherman Professor of Engineering, Emeritus, @stanford. He is 𝐓𝐮𝐫𝐢𝐧𝐠 𝐀𝐰𝐚𝐫𝐝 𝐖𝐢𝐧𝐧𝐞𝐫 of 2020. His textbooks on compilers (various editions are popularly known as the green dragon book), theory of computation (also known as the Cinderella book), data structures, and databases are regarded as standards in their fields. His interests include database theory, database integration, data mining, and education using the information infrastructure.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2023-01-01",
    time: "10:00:00",
    end_date: "2022-02-27",
    end_time: "23:00:00",
    venue: "Audi 1",
    registration_open: true,
    type: "talk",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 21,
    name: "Mrugendra Shintre",
    speaker: "Mrugendra Shintre",
    designation: "Chief Product and Technology Officer at Cleartrip",
    image:
      "https://apiv.prometeo.in/media/images/WhatsApp_Image_2022-02-26_at_5.38.12_PM.jpeg",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "NA",
    description:
      "Mrugendra is currently the Chief Product and Technology Officer at Cleartrip. Prior to this, he was the Chief Product and Technology Officer at Exxat, which is a B2B startup. Before Exxat, he spent 7+ years at Amazon in multiple leadership roles. He started his career with Cognizant. He is a Comp Sci engineer from MS University followed by an MBA from IIM Lucknow.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-02-27",
    time: "19:00:00",
    end_date: "2022-02-27",
    end_time: "20:00:00",
    venue: "Audi 1",
    registration_open: true,
    type: "talk",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 22,
    name: "Abhishek Choudhary",
    speaker: "Abhishek Choudhary",
    designation: "Solution Architect - Deep Learning, CCS",
    image: "https://apiv.prometeo.in/media/images/abhishek-choudhary.jpg",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "NA",
    description:
      "Abhishek Choudhary works as a Solution Architect - Deep Learning, CCS. He solves real-world problems with AI on the edge (IoT, Machine learning, Computer Vision, Image Processing). He has expertise in fields of AI, Machine learning, IoT.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-03-01",
    time: "11:00:00",
    end_date: "2022-03-01",
    end_time: "12:00:00",
    venue: "Audi 1",
    registration_open: true,
    type: "talk",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 23,
    name: "Basavaraja S. Vandrotti",
    speaker: "Basavaraja S. Vandrotti",
    designation:
      "Architect at Vision Research Group, Samsung R&D Institute Bengaluru.",
    image: "https://apiv.prometeo.in/media/images/20180118_172423.jpg",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "NA",
    description:
      "Basavaraja is an Architect at Vision Research Group, Samsung R&D Institute Bengaluru, where he is responsible for developing computer vision solutions for Augmented Reality. Prior to Samsung, he was with Nokia Inc., India, and the USA, with responsibilities in developing solutions for smartphones cameras and 360 degrees VR cameras. He holds a Master's degree in Signal Processing from the Indian Institute of Science (IISc) Bangalore. He has 16 years of professional experience in Computer Vision and Machine Learning, and published around 10+ international conference papers and 25+ patents, out of which many are US grants. Topic: 3D Scene Understanding: Digitizing the Real World Scenes.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-03-01",
    time: "17:00:00",
    end_date: "2022-03-01",
    end_time: "18:00:00",
    venue: "Audi 1",
    registration_open: true,
    type: "talk",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 24,
    name: "Sasikumar Ramachandran",
    speaker: "Sasikumar Ramachandran",
    designation: "Senior Solution Architect, NVIDIA",
    image: "https://apiv.prometeo.in/media/images/Sasikumar_Ramachandran.jpg",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "NA",
    description:
      "He is an experienced Senior Solutions Architect with a demonstrated history of understanding customer requirements in Visual Computing. Well-versed with AI and VR. He has expertise in the field of visual computing, technical consultancy, etc.",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-02-28",
    time: "13:00:00",
    end_date: "2022-02-28",
    end_time: "14:00:00",
    venue: "Audi 2",
    registration_open: true,
    type: "talk",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
  {
    id: 25,
    name: "Amit Kumar",
    speaker: "Amit Kumar",
    designation: "Senior Solution Architect, NVIDIA",
    image: "https://apiv.prometeo.in/media/images/amit-kumar.jpg",
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "NA",
    description:
      "He is an experienced technologist with a proven track record in AI/ML, Inventor of 4 patents and multiple publications across domains like AI, Deep Learning, Computer Vision, Founding member of HP Data Science team, hired and mentored top talent, 11 years of industrial experience and 6+ years in Data Science Specialties: • Deep Learning, Machine Learning • Natural Language Processing(NLP) • ML System Design • ML pipelines • Computer Vision, Image Processing",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-02-28",
    time: "12:00:00",
    end_date: "2022-02-28",
    end_time: "13:00:00",
    venue: "Audi 1",
    registration_open: true,
    type: "talk",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
];

export default speakerDetails;
