const flagshipEvents_data = [
  {
    id: 1,
    name: "Robowars",
    speaker: null,
    designation: null,
    bg_image:
      "https://i0.wp.com/roboticsindia.live/wp-content/uploads/2021/03/SAVE_20210324_194657.jpg",
    image:
      "https://www.nicepng.com/png/full/106-1067251_2d-game-character-png-download-2d-robot-png.png",
    cardbg1: "https://techfest.org/static/resources/robowars/robowars_bots.jpg",
    cardbg2: "https://techfest.org/static/resources/robowars/robowar60.jpeg",
    sponsors: ["https://apiv.prometeo.in/media/sponsors/smasung_sWRoaY5.webp"],
    rulebook: null,
    problem_statement: "",
    sponsor_image1: null,
    sponsor_website: null,
    participation_type: "individual",
    min_team_size: 1,
    max_team_size: 1,
    prize: "51K INR",
    description:
      "Prometeo presents Robowars! North-Western India’s Largest Robot Combat Competition where participants from around the nation battle each other for the coveted Robowars Champion Title. Come witness the most intense robot battles in India at the Robowars Championship, where participants from around the world compete for the top prize. Watch as robots clash and metal shreds in epic fights, with performances by skilled artists providing non-stop entertainment. Don't miss out on the chance to see the crowning of the ultimate Robowars Champion.The ultimate test of engineering excellence and teamwork is here! Witness the brightest engineers in India build the mightiest monsters, which shall unleash Armageddon on the battle turf!",
    poster_description: "",
    host: null,
    external_link: null,
    date: "2022-11-06",
    time: "15:11:22",
    end_date: "2022-11-06",
    end_time: "15:11:23",
    venue: null,
    registration_open: true,
    type: "technical",
    event_started: false,
    meet_link: null,
    youtube_link: null,
    webx_link: null,
    featured: false,
    rank: 1,
    hidden: false,
    presentation_template: null,
    sample_poster: null,
    submissions_started: false,
    submission_link: null,
    material_name: null,
    material: null,
  },
];
export default flagshipEvents_data;
